### ISSUE TITLE
Waka service down

### ISSUE THREAD

**Issue by haesleinhuepf** [webis-de/waka#1]
Hi @marcel-gohsen ,

Waka seems a great resource, congratulations! I just wanted to try it out, but the website is down: https://waka.webis.de/ says 502: bad gateway.

Thanks!

Best,
Robert

**Comment by marcel-gohsen** [comment]
Hey Robert,

thanks for reaching out and for the compliments. We indeed have some technical issues right now. We are currently looking into that. I'll let you know once Waka goes back online.  

Best,
Marcel

**Comment by marcel-gohsen** [comment]
Hey Robert, 

WAKA is now again up and running. Thanks for being patient, and sorry for the inconvenience. 

Let me know if you discover more problems. 

Best,
Marcel
